object Versions {
    const val coreKtx = "1.8.0"
    const val supportLibrary = "1.5.0"
    const val design = "1.8.0"
    const val constraintLayout = "2.1.4"
    const val junit = "4.13.2"
    const val junitKtx = "1.1.1-alpha05"
    const val junitExt = "1.1.5"
    const val espresso = "3.5.1"
    const val hilt = "2.42"
    const val glide = "4.13.0"
    const val glideOkhhtpIntegration = "4.0.0"
    const val shimmerEffect = "0.5.0"
    const val lifecycle = "2.4.1"
    const val collectionKtx = "1.1.0"
    const val gradleAndroidPlugin = "7.0.4"
    const val kotlin = "1.6.10"
    const val safeArgsPlugin = "2.4.1"
    const val navigationComponent = "2.4.2"
    const val jsoup = "1.13.1"
    const val retrofit = "2.9.0"
    const val kotlin_coroutine = "1.6.0"
    const val recyclerview = "1.2.1"
    const val espressoContrib = "3.1.0-alpha3"
    const val swipeRefresh = "1.1.0"
    const val timber = "5.0.1"
    const val asynclayoutinflater = "1.0.0"
    const val moshiRetrofit = "2.9.0"
    const val moshiKotlin = "1.13.0"
    const val okhttp = "3.12.0"
    const val gson = "2.8.6"
    const val room = "2.4.3"
    const val paging = "3.1.1"
    const val coroutineTest = "1.6.4"
    const val mockWebServer = "4.10.0"
    const val commonsLang = "3.9"
    const val commonsCollections = "4.4"
    const val commonsIO = "2.6"
    const val chucker = "3.5.2"
    const val firebaseBom = "30.2.0"
    const val sdp = "1.0.6"
    const val flexbox = "3.0.0"


}